---
- name: Validate SSH configuration
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Reload SSH

- name: Reload SSH
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded
  listen: Reload SSH

- name: Reload NetBird Docker firewall
  ansible.builtin.systemd_service:
    name: netbird-docker-firewall
    enabled: true
    state: restarted
    daemon_reload: true
  listen: Reload NetBird Docker firewall
